# Generated by Django 2.0.5 on 2019-01-09 15:14

import apps.users.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.users.models.QueryUserManager()),
                ('active', apps.users.models.QueryUserManager(is_active=True)),
                ('reviewable', apps.users.models.QueryUserManager(is_reviewable=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_reviewable',
            field=models.BooleanField(default=True, help_text='Пишет self-review и получает обратную связь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL),
        ),
    ]
