# Generated by Django 2.2.3 on 2020-01-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_noop'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
