# Generated by Django 2.0.5 on 2018-06-28 12:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('pending', 'pending'), ('started', 'started'), ('finished', 'finished')], default='pending', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Квартал',
                'verbose_name_plural': 'Кварталы',
                'ordering': ['-name'],
                'get_latest_by': 'name',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('status', model_utils.fields.StatusField(choices=[('requested', 'Запросил'), ('draft', 'Черновик'), ('rejected', 'Требует доработки'), ('pending', 'Ожидает одобрения менеджера'), ('hidden', 'Скрыт от сотрудника'), ('published', 'Виден сотруднику')], default='draft', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('text', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('score', models.CharField(blank=True, choices=[('5', 'Сильно превышает ожидания'), ('4', 'Превышает ожидания'), ('3', 'Соответствует ожиданиям'), ('2', 'Ниже ожиданий'), ('1', 'Сильно ниже ожиданий'), ('-', 'Не взаимодействовал, оценить не могу')], max_length=2, null=True)),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=128)),
                ('expectations', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='SelfReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('text', models.TextField()),
                ('comment', models.TextField(blank=True)),
                ('status', model_utils.fields.StatusField(choices=[('draft', 'Черновик'), ('rejected', 'Требует доработки'), ('pending', 'Ожидает одобрения менеджера'), ('published', 'Готово')], default='draft', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('interval', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reviews.Interval')),
            ],
            options={
                'verbose_name': 'Self-review',
                'verbose_name_plural': 'Self-review',
            },
        ),
    ]
