# Generated by Django 2.0.5 on 2018-07-13 07:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0002_auto_20180628_1204'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='selfreview',
            unique_together={('interval', 'user')},
        ),
    ]
