# Generated by Django 2.0.5 on 2019-01-09 14:44

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20180713_0720'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='interval',
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
