# Generated by Django 2.2.3 on 2019-11-19 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_noop'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='interval',
            managers=[
            ],
        ),
    ]
