# Generated by Django 2.2.3 on 2019-11-19 17:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20191119_1748'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='goal',
            unique_together={('interval', 'target')},
        ),
    ]
